config/routes.rb
Rails.application.routes.draw do
  resources :loans

  resources :sales

  resources :customers

  resources :employees

  resources :quotes

  resources :cars

  resources :sales_statuses

  resources :quote_statuses

  resources :emp_positions

  resources :colors

  resources :years

  resources :makes

  root 'sales#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :quotes
  belongs_to :color
  belongs_to :make
  belongs_to :year

  def getModel
    "#{make.make_name}"
  end
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :cars
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales
end

app/models/emp_position.rb
class EmpPosition < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :emp_position
  has_many :sales
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :quote

  def quotenameandprice
    "#{quote.quote_name} #{quote.quote_price}"
  end

  def quotecalculation
    i= interest_rate/100
    p= quote.quote_price
    t= terms * 12
    m = ((i * p * (1+i)**t)/(((1+i)**t)-1))
    return m
  end

  def quotetable
    i= interest_rate/100
    b= quote.quote_price
    t= terms * 12
    m= ((i * b * (1+i)**t)/(((1+i)**t)-1))
    mir= interest_rate/12
    mi= mir * b
    p= m - mi

    end

  end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :cars
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :quote_status
  has_many :sales
  belongs_to :car
  has_many :loans


end

app/models/quote_status.rb
class QuoteStatus < ActiveRecord::Base
  has_many :quotes
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :quote
  belongs_to :sales_status, :foreign_key => "sale_status_id"
  belongs_to :employee
  belongs_to :customer


  def quotetax
    w = 0.1
    t = 0.043
    q = quote.quote_price
    e = ((q*w) + q)
    total = (e + (e * t))
    return total
  end
end

app/models/sales_status.rb
class SalesStatus < ActiveRecord::Base
  has_many :sales
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cars
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:quote_id, :customer_id, :employee_id, :sale_status_id, :date, :total)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_id %><br>
    <%= f.collection_select :quote_id, Quote.all, :id, :quote_name %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id , :name %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select :employee_id, Employee.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :sale_status_id %><br>
    <%= f.collection_select :sale_status_id, SalesStatus.all, :id, :status_type %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Customer</th>
      <th>Employee</th>
      <th>Sale status</th>
      <th>Date</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.quote.quote_name %></td>
        <td><%= sale.customer.name %></td>
        <td><%= sale.employee.name %></td>
        <td><%= sale.sales_status.status_type %></td>
        <td><%= sale.date %></td>
        <td><%= sale.quotetax %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @sale.quote.quote_name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer.name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @sale.employee.name %>
</p>

<p>
  <strong>Sale status:</strong>
  <%= @sale.sales_status.status_type%>
</p>

<p>
  <strong>Date:</strong>
  <%= @sale.date %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale.quotetax %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>